### ISSUE TITLE
Configure webpack & dev environment

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/less-css-helper-library#3]
Configure dev environment with/for the following:
- [x] eslint
- [x] express
- [x] babel
- [x] webpack

Setup:
- [ ] lite-server or webpack-dev-server
- [x] Bundling
- [ ] Minification

**Comment by Ifycode** [comment]
Useful resources:
* https://stackoverflow.com/a/52874215

**Comment by seunbayo** [comment]
Have started to work on this issue?if no assign to me

**Comment by Ifycode** [comment]
@seunbayo Yes please work on it. Thank you. I've assigned it to you.

**Comment by Ifycode** [comment]
I have assigned you to issue #6 @seunbayo 

This is a collective issue. What part of this issue have you started working on? 

I ask so that I can create a separate issue for it and assign you to it there (not here).

**Comment by seunbayo** [comment]
I see that some of them have been ticked
It's only the webpack dev server set up and modification that is remaining.

**Comment by Ifycode** [comment]
Yes. But the idea is that different things should be fixed in different pull requests. I wouldn't want both to be tackled in the same pull request since they are different things. So that's why I would be opening separate issues for them. So that it's one pull request per issue. It makes review easier.

So I've created issue #7 for the dev server part. If you wish to send a PR for that, just reference the that issue in the PR.

But issue #5 may need to be solved before minification. Let me know your thoughts.

**Comment by seunbayo** [comment]
You know what, close all the issue and open a fresh issue for each left.

Let's take it one after the other

**Comment by Ifycode** [comment]
I have separated the issues already:

* Issue #5
* issue #6 
* issue #7 

You can choose from any and start working on those @seunbayo 
After these we can talk of opening some other ones.

**Comment by Ifycode** [comment]
You can also raise an issue, if you find one that hasn't been listed there already.

**Comment by Ifycode** [comment]
The less-css-helper-library is now depreciated, will be archived soon and deleted later on. 

Contribute to the [styles-library](https://github.com/code-collabo/styles-library) instead which is actively in development. Closing this issue as it has unfinished tasks from here have been transferred to the styles-library: 
- [@code-collabo/styles-library#4](https://github.com/code-collabo/styles-library/issues/4).
- [@code-collabo/styles-library#12](https://github.com/code-collabo/styles-library/issues/12).
