### ISSUE TITLE
Transpile JS bundle generated down to es5

### ISSUE THREAD

**Issue by Ifycode** [code-collabo/less-css-helper-library#6]
#### Describe issue
The JS bundle generated hasn't been transpiled down to es5.

#### Task
Transpile JS bundle generated down to es5 using babel.

**Comment by seunbayo** [comment]
I am interested in picking this up

**Comment by Ifycode** [comment]
@seunbayo sorry for the late reply. Yes please go ahead. Assigned to you.

**Comment by Ifycode** [comment]
The less-css-helper-library is now depreciated, will be archived soon and deleted later on. 

Contribute to the [styles-library](https://github.com/code-collabo/styles-library) instead which is actively in development. Closing this issue as it has been transferred to the styles-library [@code-collabo/styles-library#11](https://github.com/code-collabo/styles-library/issues/11).
